SpecialPower SpecialPower_LUAScriptTrigger
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_ExecuteMenuSelection
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_MenuSelectionUp
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_MenuSelectionDown
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_MenuSelectionRight
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_MetaMenuSelectionLeft
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_MetaMenuOpen
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End