SpecialPower SpecialPower_LUAScriptTrigger
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_ExecuteMenuSelection
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_MenuSelectionUp
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_MenuSelectionDown
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_MenuSelectionRight
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_MetaMenuSelectionLeft
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPower_MetaMenuOpen
	Enum				= SPECIAL_GENERAL_TARGETLESS
	ReloadTime		= 0
End

SpecialPower SpecialPowerEdgeCoordinateAnchorUpperRight
	Enum		= SPECIAL_AT_VISIBLE_OBJECT
	ReloadTime = 0
End
	
SpecialPower SpecialPowerEdgeCoordinateAnchorUpperLeft
	Enum		= SPECIAL_AT_VISIBLE_OBJECT
	ReloadTime = 0
End
	
SpecialPower SpecialPowerEdgeCoordinateAnchorDownRightSpawner
	Enum		= SPECIAL_AT_VISIBLE_OBJECT
	ReloadTime = 0
End

SpecialPower SpecialPowerEdgeCoordinateAnchorDownRight
	Enum		= SPECIAL_AT_VISIBLE_OBJECT
	ReloadTime = 0
End
	
SpecialPower SpecialPowerChoosePosition
	Enum		= SPECIAL_AT_VISIBLE_OBJECT
	RadiusCursorRadius = 10
	ReloadTime = 0
End	