CommandSet MetaMenuCommandSet
	1 = Command_ExecuteMenuSelection
	2 = Command_MenuSelectionUp
	3 = Command_MenuSelectionDown
	4 = Command_MenuSelectionRight
	5 = Command_MetaMenuSelectionLeft
	6 = Command_LUAScriptTrigger
	7 = Command_ExecuteMenuSelectionSideBar
End

CommandSet MetaControlEdgeCoordinateAnchorDownLeftCommandSet
	1 = Command_SpecialPowerEdgeCoordinateAnchorUpperRight
End

CommandSet MetaControlEdgeCoordinateAnchorDownRightSpawnerCommandSet
	1 = Command_SpecialPowerEdgeCoordinateAnchorDownRight
End

CommandSet MetaControlEdgeCoordinateAnchorDownRightCommandSet
	1 = Command_SpecialPowerEdgeCoordinateAnchorUpperLeft
End
